### PR TITLE
1225: add smeshing color indicator

### LINKED ISSUE #1225: Add an indicator to the smeshing tab to indicate smeshing status
### Environment
Smapp version: 0.xx.x | develop
Node version: v0.x.xx 
OS: Windows 10 | macOS High Sierra (10.13) | Ubuntu 20.04
Describe the bug
Currently, there is no clear indicator on the smeshing tab to indicate whether the smeshing process is running smoothly or if there are any issues. This can make it difficult for users to identify if there are any problems with the smeshing process.

### Steps to reproduce
- [] Run the node
- [] Set up the PoS ( Smeshing tab ) 
- [] Check the indicator

### Expected behavior
An indicator (green/orange/red) should be added to the smeshing tab, similar to the network tab, to provide a clear indication of the status of the smeshing process. Green should indicate that smeshing is running smoothly, orange should indicate that a file is being created, and red should indicate that there is an issue with the smeshing process.

### Actual behavior
Currently, there is no clear indicator on the smeshing tab to indicate the status of the smeshing process.

### Logs
N/A

### How to fix
To fix this issue, an indicator (green/orange/red) should be added to the smeshing tab. The indicator should be updated in real-time to reflect the current status of the smeshing process. When smeshing is running smoothly, the indicator should be green. When a file is being created, the indicator should be orange. When there is an issue with the smeshing process, the indicator should be red.

### PR DESCRIPTION
**Pull request by maparr**
It closes #1225 

https://user-images.githubusercontent.com/54288612/234843063-db362205-04af-4df9-9741-179a78973a8c.mov

### CODE REVIEW

File: app/screens/main/Main.tsx [hunk 1]
```diff
@@ -148,13 +150,20 @@ class Main extends Component<Props, State> {
   }
 
   render() {
-    const { nodeError, status, genesisID, theme } = this.props;
+    const { nodeError, status, genesisID, theme, smesher } = this.props;
+
+    // eslint-disable-next-line no-nested-ternary
+    const smeshingIndicatorColor = smesher.isSmeshingStarted
```
Comment (brusherru) [inline app/screens/main/Main.tsx]: Since we have an indicator here, I think we need to show these statuses:
1. Green: All good, initialized, and smeshing
2. Orange: initializing
3. Red: error(?) or paused
4. Grey: not started

I think you can check for `isSmeshingStarted` and `postSetupState`.

**Comment by maparr** [comment]
need to test this task with GPU to get the smeshing state finished.

**Review by monikasmolarek — APPROVED** [review]

**Review by brusherru — APPROVED** [review]
