### PR TITLE
Fix: Opening the same wallet creates additional records 

### LINKED ISSUE #1330: Opening the same wallet creates additional records
### Environment

* Smapp version: any
* Node version: any
* OS: any

### Describe the bug

Having one wallet logged in in Smapp, and then restoring a wallet from file - if we pick the same wallet that is already logged in, it will be added as a second wallet, then we can repeat it. There's no warning that we are opening the same wallet / there's no distinction between the records in the dropdown on the login page, the doubles are not marked/removed. 

### Steps to reproduce

1.  Open smapp and log in with one wallet
2.  backup this wallet to the file 
3.  open existing wallet / settings->restore wallet - choose the backup file you just created
4. try copying the wallet file to another location and open it again, repeat it 

### Expected behavior

If we open the same wallet that is already opened, it should not be possible or at least marked somehow as a double on the login screen. 

### Actual behavior

Screenshot 2023-07-10 at 01 06 17

### Logs
let me know if needed

### PR DESCRIPTION
**Pull request by maparr**
It closes #1330

### CODE REVIEW

File: app/screens/auth/UnlockWallet.tsx [hunk 1]
```diff
@@ -135,15 +171,32 @@ const UnlockWallet = ({ history, location }: AuthRouterParams) => {
...
+        description: `CREATED: ${convertISOToDate(
+          meta.created
+        )} | NETWORK: ${networkName}`,
+        endAdornment: (
+          <>
+            {copiedPath === path ? (
+              <CopiedBanner>Wallet path copied</CopiedBanner>
+            ) : (
+              <CopiedButtonWrapper>
+                <CopyButton secondary value={path} onClick={setCopiedPath} />
```
Comment (brusherru) [inline app/screens/auth/UnlockWallet.tsx]: I believe "Reveal in Finder" will be more handy for a common user.
You can use the folder icon for it.
Also, you won't need an additional state and animation.

File: app/hooks/useImportFileWarning.ts [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+        similarities.push('encrypted data');
+      }
+
+      let formattedMessage = 'A wallet with the same ';
+      if (similarities.length > 0) {
+        formattedMessage += similarities.join(', ');
+      } else {
+        formattedMessage = 'A wallet';
+      }
+      formattedMessage += ' already exists.';
```
Comment (monikasmolarek) [inline app/hooks/useImportFileWarning.ts]: @brusherru will for sure assess it better. I don’t have proper knowledge, but to me, it seems this could be improved. The final message does not sound really well and it's hard to correct. 
My suggestion (keep in mind that I know almost nothing about the TS/JS.
```suggestion
      const { isDuplicateName, isDuplicateWallet, isDuplicatePath } = payload;

    let formattedMessage = '';

    if (isDuplicateWallet || isDuplicatePath) {
      // If the wallet or/and path is duplicated, regardless of name duplication
      formattedMessage = "This wallet is already opened. Do you want to import it anyway?";
    } else if (isDuplicateName) {
      // If only the name is duplicated, the path or encrypted data different
      formattedMessage = "A different wallet with the same name is already opened in Smapp. Double-check which one you use and consider renaming one of them.";
    }
```

File: app/screens/modal/ImportFileWarningModal.tsx [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+
+const ImportFileWarningModal = () => {
+  const { isOpen, message, handleResponse } = useImportFileWarning();
+
+  if (!isOpen) return null;
+
+  return (
+    <Modal
+      header="Import File Warning"
+      subHeader="Please Confirm File Import"
```
Comment (monikasmolarek) [inline app/screens/modal/ImportFileWarningModal.tsx]:
```suggestion
      header="CONFIRM FILE IMPORT"
      subHeader=" "
```

I left the subheader like that because the "--" separator inserted with the `subheader` looks very well and in general the modal layout is prettier. But there's most probably a better way ti implement it.

File: app/screens/modal/ImportFileWarningModal.tsx [hunk 4]
```diff
@@ -0,0 +1,50 @@
...
+      width={600}
+      height={300}
+    >
+      <Message>{message}</Message>
+      <ButtonsWrapper>
+        <Button
+          isPrimary={false}
+          onClick={() => handleResponse(true)}
+          text="CONFIRM"
```
Comment (monikasmolarek) [inline app/screens/modal/ImportFileWarningModal.tsx]:
```suggestion
          text="IMPORT"
```

**Review by monikasmolarek — CHANGES_REQUESTED** [review]
Additionally : 
After we Cancel the import, can we fall to this screen:
image
instead of stating "Incorrect file"? 
image

Or it's too complicated/ time consuming to implement?

**Comment by maparr** [comment]
> Additionally : After we Cancel the import, can we fall to this screen: image instead of stating "Incorrect file"? image
> 
> Or it's too complicated/ time consuming to implement?

should work as expected right now

**Review by monikasmolarek — DISMISSED** [review]
👌

File: shared/types/guards.ts [hunk 5]
```diff
@@ -83,3 +84,7 @@ export const isWalletFile = (wallet: any): wallet is WalletFile =>
   isWalletMeta(wallet.meta) &&
   (isWalletGCMEncrypted(wallet.crypto) ||
     isWalletLegacyEncrypted(wallet.crypto));
+
+export const isGenesisIDMissing = (wallet: Wallet) =>
+  !wallet?.meta?.genesisID?.length;
+export const isApiMissing = (wallet: Wallet) => !wallet.meta.remoteApi;
```
Comment (brusherru) [inline shared/types/guards.ts]: Max, it's not type guards.
Please move it to the `walletValidation` module.
And read about type guards. They should only checking for an argument representing some specific type. e.g. `isWallet = (a: any): a is Wallet`

File: desktop/main/walletFile.ts [hunk 6]
```diff
@@ -276,29 +278,35 @@ export const copyWalletFile = async (filePath: string, outputDir: string) => {
...
+        return wallet.meta ? { path: filePath, wallet } : null;
       } catch (err) {
-        return { path: filePath, error: err };
+        return null;
       }
     })
-  ).then(
-    // TODO: Show error to the user?
-    (res) => R.filter(R.has('meta'), res)
+  ).then(R.reject<WalletWithPath | null>(R.isNil)) as Promise<WalletWithPath[]>;
```
Comment (brusherru) [inline desktop/main/walletFile.ts]: Such cast may cause problems because TS does not check for props overlapping... for example, you can cast it into `Promise<string[]>` and TypeScript would not warn you.

I guess there might be some point-free solution for correct typing, but I believe more clear and readable will be like this:
```suggestion
  ).then((x: (WalletWithPath | null)[]) => R.reject(R.isNil, x));
```

File: shared/types/wallet.ts [hunk 7]
```diff
@@ -80,3 +80,13 @@ export interface WalletFile {
   meta: WalletMeta;
   crypto: WalletSecretsEncrypted;
 }
+
+export interface WalletWithPath {
+  path: string;
+  wallet: WalletFile;
+}
```
Comment (brusherru) [inline shared/types/wallet.ts]: Name it more concrete: `WalletWithPath` -> `WalletFileWithPath`

File: tests/desktop/walletValidation.ts
Comment (brusherru) [inline tests/desktop/walletValidation.ts:1]: Rename to `walletValidation.spec.ts`

File: desktop/main/Wallet.ts [hunk 8]
```diff
@@ -37,6 +44,57 @@ const list = async () => {
...
+) => {
+  try {
+    const oldWalletFiles = StoreService.get('walletFiles');
+    const newWalletData = await loadRawWallet(filePath);
+    const existingWallets = await loadRawWallets(oldWalletFiles);
+    const isDuplicateName = hasDuplicateName(newWalletData, existingWallets);
+    const isDuplicateWallet = hasDuplicateCipherText(
+      newWalletData,
+      existingWallets
+    );
```
Comment (brusherru) [inline desktop/main/Wallet.ts]: It is still `O(N^m)` complexity where `m` is a validation by one specific property, while it can be done as `O(N)`...

But ok, let's keep it as is, Users are not supposed to have a lot of wallet files and these validations should be pretty easy...

**Review by brusherru — CHANGES_REQUESTED** [review]
It is working well.
But it should be polished — check out comments.

p.s.
To be honest, I don't like the excessive complexity of this solution:
- the main process may send message and title to the renderer process (instead of some lists)
- renderer process may have only one Component to display a generic prompt/warning popup and then just display what were sent from main process, instead of having a custom component and a custom hook

Probably we can leave it as is for now, and next time we will need a new warning/prompt — I will implement a generic solution and refactor it.

**Review by monikasmolarek — APPROVED** [review]
works as expected, ok from the user perspective

**Review by brusherru — APPROVED** [review]
LGTM
