### PR TITLE
Fix bugs with switching between wallet modes

### LINKED ISSUE #1052: Creating Wallet only or changing app mode impossible on devnet 310?
### Environment

- Smapp version: 0.2.10 | prerelease + v0.2.9-pr.1032
- Node version: v0.2.19-beta.0
- OS: Windows 10 Home + macOS Ventura Version 13.0.1
- devnet 310

### Describe the bug

After over 2 hours of waiting, no success in setting up the Wallet only (remote API). The same while changing the application mode (from settings) from the local node to Wallet only. 
After Smapp restart, the mode is changed to Wallet only, but the app crashes, the "set up smesher button" doesn’t work, and in general, the resources usage peaks. 

### Steps to reproduce

1. Open Smapp and click "Create" to set up a new wallet. 
2. Choose "Wallet Only" and proceed with the rest of the steps. 
3. Alternatively, when logged in, go to settings, section 'Wallets". 
4. In the "Application mode" click "Switch to Wallet Only"

### Expected behavior

There should be an option to use Smapp without running a local node. If the "Wallet only" option is chosen, Smapp should connect to remote API. 

### Actual behavior

After over 2 hours of waiting with the loading screen, there was no success in connecting to the remote API. 

Screenshot 2022-12-21 at 22 14 10

Screenshot 2022-12-21 at 22 14 37

After Smapp restart on v0.2.9-pr.1032 on MacOs:
Screenshot 2022-12-21 at 22 37 53
But the "Set up Smesher" button does not work or even makes the App crash/slow down dramatically. 

v0.2.10 on Win, even after app restart the mode was not changed (if triggered from settings).

### Logs

[app-log.0.2.9-pr.1032.old.txt](https://github.com/spacemeshos/smapp/files/10281827/app-log.0.2.9-pr.1032.old.txt)
[app-log.0.2.9-pr.1032.txt](https://github.com/spacemeshos/smapp/files/10281828/app-log.0.2.9-pr.1032.txt)

[spacemesh-log-1e0acdbd58480f738940959cb6c5554e728a739d.txt](https://github.com/spacemeshos/smapp/files/10281815/spacemesh-log-1e0acdbd58480f738940959cb6c5554e728a739d.txt)

### How to fix 

n/a

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #1052
Details:
- opening wallets of different types works smoothly now
- optimized querying of txs and rewards
- fixed managing the smesher service (turn off / on, etc)
- fixed <UnlockWallet> component
- enlarged grpc query batch size to 100 results
- some tiny fixes
- feat: added filter dropdown on Transaction Log screen. Now User is able to choose what to see: all / txs / rewards.

It also may fix some of these issues (pls, check it out):
- #1066 
- #1049

### CODE REVIEW

File: shared/types/guards.ts [hunk 1]
```diff
@@ -41,7 +41,13 @@ export const isTx = (a: any): a is Tx =>
...
 
 export const isReward = (a: any): a is Reward =>
-  a && a.layer && a.coinbase && a.amount;
+  a &&
+  a.layer &&
+  a.coinbase &&
+  a.amount &&
+  typeof a.coinbase === 'string' &&
+  typeof a.layer === 'number' &&
+  typeof a.amount === 'number';
```
Comment (maparr) [inline shared/types/guards.ts]:
```suggestion
  typeof a.?coinbase === 'string' &&
  typeof a.?layer === 'number' &&
  typeof a.?amount === 'number';
```

**Review by monikasmolarek — CHANGES_REQUESTED** [review]
Both Mac and Win OS

Creating a Wallet Only from scratch OK

Switching mode from settings to Wallet+Node to be fixed:

- [ ] Smeshing screen should be empty-ready to set up POS, I tested on all new and clear SMAPP, no chance to have any remainings from previous actions. 
- [ ] Switching back to Wallet Only skipped the password validation
- [ ] After Node sync, trying to set up a correct POS data triggers: _Unhandled error in action:
Error invoking remote method 'SMESHER_STOP_SMESHING': No handler registered for 'SMESHER_STOP_SMESHING'_
- [ ]  Couldn't test the transactions filtering properly because smeshing is not possible as of now, but seems to be working correctly. 


https://user-images.githubusercontent.com/89876259/210090041-762f0bc3-a844-41c8-b871-52a1f979b082.mp4




[app-log.0.2.9.txt](https://github.com/spacemeshos/smapp/files/10325680/app-log.0.2.9.txt)
[spacemesh-log-55dc4325e8d7f8f9824a47d646599420a2cf4516.txt](https://github.com/spacemeshos/smapp/files/10325691/spacemesh-log-55dc4325e8d7f8f9824a47d646599420a2cf4516.txt)

**Comment by brusherru** [comment]
I've tested Smapp on macOS and windows 11, and on both Smapp seems working fine.
It still has some bugs in edge cases, mostly related to switching between networks.
However, restarting Smapp fixes the problem.
I believe it is good enough to make the long-awaited release.

@monikasmolarek could you check out mentioned problems there and open issues if needed?
