### PR TITLE
Filled the visible tooltips with content. ad #1057

### LINKED ISSUE #1057: Tooltips to be updated
### Environment

- Smapp version: 0.2.10 | prerelease + v0.2.9-pr.1032
- Node version: v0.2.19-beta.0
- OS: Windows 10 Home + macOS Ventura Version 13.0.1

### Describe the bug

All the tooltips to be filled with the actual content.

### Steps to reproduce

Hove over any tooltip in the SMAPP application. 

### Expected behavior

There should be actual info/help for the User. It should help instantly without having to visit the website.

### Actual behavior

As for now we can find there only some random/mockup texts. 

Screenshot 2022-12-22 at 18 58 45
Screenshot 2022-12-22 at 18 59 25

### Logs
 
N/A

### How to fix 

Add the useful information to the tooltips.

### PR DESCRIPTION
**Pull request by monikasmolarek**
I tried to help with the [#1057 ](https://github.com/spacemeshos/smapp/issues/1057)

Probably due to my incorrect/insufficient understanding of some aspects, some information should be corrected. 

As Kirill mentioned, the content should be also reviewed by Yael.

### CODE REVIEW

**Comment by maparr** [comment]
fix for #1057

File: app/components/node/PoSSize.tsx [hunk 1]
```diff
@@ -160,7 +163,10 @@ const PoSSize = ({
       <Row>
         <Icon2 src={posRewardEst} />
         <Text>Estimated coin reward</Text>
-        <Tooltip width={200} text="Some text" />
+        <Tooltip
+          width={250}
+          text="The amount of the rewards is unpredictable. It depends on the number of blocks contributed by the miner, and on the total number of blocks contributed in that layer."
```
Comment (brusherru) [inline app/components/node/PoSSize.tsx]: Afaik, it is actually predictable, but [it is not implemented](https://github.com/spacemeshos/go-spacemesh/blob/d1303c36716e175a734766adb24780798c08bc3e/api/grpcserver/smesher_service.go#L163-L167) :)

File: app/screens/auth/Leaving.tsx [hunk 2]
```diff
@@ -88,12 +88,15 @@ const Leaving = ({ history }: AuthRouterParams) => {
           <ComplexLink>
             <Link onClick={navigateToSetupGuide} text="SETUP GUIDE" />
             <Row>
-              <Text>DON`T HAVE A DESKTOP?</Text>
+              <Text>DON`T HAVE A DESKTOP? &nbsp;</Text>
               <Link
-                onClick={() => history.push(AuthPath.Recover)}
+                onClick={() => history.push(AuthPath.Recover)} // Shouldn't it trigger set up instead of recover?
```
Comment (brusherru) [inline app/screens/auth/Leaving.tsx]: 👍 
We show this screen when the User tries to leave creating a wallet flow. So it seems reasonable to have a link to recover, but the text is misleading.
Let's replace it to "ALREADY HAVE A WALLET? [RECOVER IT]"?

File: app/screens/auth/Leaving.tsx [hunk 3]
```diff
@@ -88,12 +88,15 @@ const Leaving = ({ history }: AuthRouterParams) => {
...
                 text="SETUP WALLET ONLY"
               />
-              <Tooltip width={100} text="SETUP WALLET ONLY" />
+              <Tooltip
+                width={140}
+                text="You will be able to send and receive SMH."
```
Comment (brusherru) [inline app/screens/auth/Leaving.tsx]: And then probably this tooltip is excessive and we can just get rid of it.
Or at least write there about recovering options:
```suggestion
                text="You can recover your wallet from file or mnemonics"
```

File: app/screens/auth/WalletConnectionType.tsx [hunk 4]
```diff
@@ -114,7 +114,7 @@ const WalletConnectionType = ({ history, location }: AuthRouterParams) => {
             <Row>
               <Icon />
               <RowTitle>WALLET + NODE</RowTitle>
-              <Tooltip width={100} text="WALLET + NODE" />
+              <Tooltip width={120} text="To send, receive and mine SMH" />
```
Comment (brusherru) [inline app/screens/auth/WalletConnectionType.tsx]: Not sure it is more clear, but usually we're calling it "smeshing" (like setting up smeshing / instead of setting up mining), so let's be consistent.
```suggestion
              <Tooltip width={120} text="To send, receive and smesh coins" />
```

File: app/screens/network/Network.tsx [hunk 5]
```diff
@@ -138,7 +138,10 @@ const Network = ({ history }) => {
       <DetailsRow>
         <DetailsTextWrap>
           <DetailsText>Age</DetailsText>
-          <Tooltip width={250} text="tooltip age" />
+          <Tooltip
+            width={250}
+            text="​​Elapsed time since the current Network deployment"
```
Comment (brusherru) [inline app/screens/network/Network.tsx]: I think that deployment sounds good for devnets, but for the mainnet/testnet "genesis" is a better term, since it should not change after the genesis :)
```suggestion
            text="​​Elapsed time since the current Network genesis"
```

**Review by maparr — DISMISSED** [review]
LGTM!

File: app/screens/network/Network.tsx [hunk 6]
```diff
@@ -199,7 +211,10 @@ const Network = ({ history }) => {
         <DetailsRow>
           <DetailsTextWrap>
             <DetailsText>Connected neighbors</DetailsText>
-            <Tooltip width={250} text="tooltip Connected neighbors" />
+            <Tooltip
+              width={250}
+              text="Number of connected peers. Spacemesh multiplexes messages from many subprotocols (gossip, discovery, hare, sync) over each P2P connection."
```
Comment (brusherru) [inline app/screens/network/Network.tsx]: Not sure we need to describe such technical details here.
Mb something like this? 🤔 
```suggestion
              text="Spacemesh syncs database and participate in the network by communicating with other connected peers"
```

@yaelmhoffman do you have any ideas about it? :)

**Review by brusherru — COMMENTED** [review]
I left some comments.
In the rest, all is good!

File: app/components/node/PoSSize.tsx (hunk 1 above)
Comment (brusherru) [reply app/components/node/PoSSize.tsx]: By the way, we just agreed with @pigmej that I will hide this row until we have this API endpoint implemented :)

File: app/screens/network/Network.tsx [hunk 7]
```diff
@@ -149,7 +152,7 @@ const Network = ({ history }) => {
           <DetailsText>Genesis ID</DetailsText>
           <Tooltip
             width={250}
-            text="Unique hash per network, generated from genesis time and unique identifier."
+            text="Unique hash per network, generated from genesis time and unique identifier"
```
Comment (yaelmhoffman) [inline app/screens/network/Network.tsx]: Suggested change:

Unique hash per network, generated from genesis time and a unique identifier

File: app/screens/network/Network.tsx [hunk 8]
```diff
@@ -173,21 +176,30 @@ const Network = ({ history }) => {
...
         </DetailsTextWrap>
         <GrayText>{status?.topLayer || 0}</GrayText>
       </DetailsRow>
       <DetailsRow>
         <DetailsTextWrap>
           <DetailsText>Verified Layer</DetailsText>
-          <Tooltip width={250} text="tooltip Verified Layer" />
+          <Tooltip
+            width={250}
+            text="Number of the last processed and synced Layer"
```
Comment (yaelmhoffman) [inline app/screens/network/Network.tsx]: Suggested change: The last processed and synced Layer number. Usually lags behind "Current Layer" by a layer or two.

**Comment by brusherru** [comment]
I've fixed lint errors and rebased it on develop branch ;)

**Review by brusherru — APPROVED** [review]
LGTM

**Review by maparr — APPROVED** [review]
