### PR TITLE
Fix small UI bugs

### LINKED ISSUE #777: Inconsistent balance amount display while syncing
Repro:
1. Start the app in dev mode w/o any local data
2. Go to wallet screen: balance label is `Syncing...` - good.
3. Restart the app
4. Go to wallet screen

Result: `0 SMH` balance is displayed
Expected: Display `Syncing...` like in the first session. Only display an actual balance amount when node is synced and such a balance was retrieved from the api in this app session.

### PR DESCRIPTION
**Pull request by brusherru**
It fixes #777, #778, #780, #774.

### CODE REVIEW

**Comment by avive** [comment]
I'm verifying the UI fixes and came across this: I killed the go-sm process to validate network screen layout. I got a dialog box when process was killed (below). Will it only be displayed in dev mode? It should. 

Screen Shot 2021-08-02 at 11 17 42 AM

I'm confirming that the UI fixes for all the UI issues mentioned in this have been fixed.

@brusherru

**Comment by brusherru** [comment]
> Will it only be displayed in dev mode?

Yep, it is dev-mode only.

**Comment by avive** [comment]
@IlyaVi - I have no more UX related feedback - this can be merged when the code has been code reviewed.

File: app/screens/wallet/SendCoins.tsx [hunk 1]
```diff
@@ -91,41 +91,44 @@ const SendCoins = ({ history, location }: Props) => {
...
+          />
+        ) : (
+          <TxSummary address={address} fromAddress={currentAccount.publicKey} amount={parseInt(`${amount}`)} fee={fee} note={note} key="summary" />
+        )}
+      </>
+    );
   };
 
   switch (mode) {
+    default: // Hopefully it never defaults, but in case that this happened at least render a first step
```
Comment (IlyaVi) [inline app/screens/wallet/SendCoins.tsx:131]: a bug can be hidden by this change

Comment (brusherru) [reply app/screens/wallet/SendCoins.tsx:131]: Do you think that is an empty screen is better than render something for such a case?
Moreover, `mode` has an explicit type `1 | 2 | 3` and mode handling implemented right in the component (no possible side-effects on this variable), so TypeScript should help us to avoid the case for `default`.
But it's better to have a `default` case for switches, much better than shut up eslint :)

**Review by IlyaVi — APPROVED** [review]
