### PR TITLE
Fix: Persisting error modal after wrong file uploaded as wallet

### LINKED ISSUE #1477: Persisting error modal after wrong file uploaded as wallet
### Environment

* Smapp version: any
* Node version: any
* OS: any

### Describe the bug

If we try to open a wallet from a file but choose the incorrect file - any non-empty JSON, smapp will accept it and try to proceed. Of course will not be able to parse it, so we can retry to load the correct file, but once we log out, we get the error modal that persists even after smapp restart. Sometimes we get this error immediately. Only unlinking the wrong file helps to get smapp usable again. 

### Steps to reproduce

1.  Open Smapp
2.  Try to recover wallet from file
3.  Pick any non-empty JSON file
4. try lo log in, wait or try to load the correct file, if still no modal, just log out. 
5. try to restart smapp

### Expected behavior

smapp should drop the file it could not parse (immediately or after app restart), we should be able to use smapp without restraints

### Actual behavior

error modal persists even after restart

https://github.com/spacemeshos/smapp/assets/89876259/81efac7f-5bc0-481a-8665-fec079a719e1

### Logs

[app-log.1.1.1.txt](https://github.com/spacemeshos/smapp/files/12457677/app-log.1.1.1.txt)
[spacemesh-log-7c8cef2b.txt](https://github.com/spacemeshos/smapp/files/12457678/spacemesh-log-7c8cef2b.txt)

### PR DESCRIPTION
**Pull request by maparr**
it closes #1477 

### How to test
the same scenario as here #1477 
 

Screenshot 2023-11-01 at 18 57 45

Screenshot 2023-11-01 at 18 12 51

### CODE REVIEW

File: app/components/auth/DragAndDrop.tsx
Comment (brusherru) [inline app/components/auth/DragAndDrop.tsx:1]: How to reproduce the mentioned "undefined if no files" issue?
As I know, it will be an empty string by default.
So, if I'm wrong — describe a way to reproduce and change Props type to a proper one.

File: app/redux/wallet/actions.ts [hunk 1]
```diff
@@ -275,15 +275,26 @@ export const restoreFile = ({ filePath }: { filePath: string }) => async (
...
+      filePath
+    );
+
+    if (!isValidationSuccessful) {
+      const errorMessage = `Wallet file ${filePath} is invalid.\nPlease verify it and import the wallet file once again.`;
+      dispatch(setUiError(new Error(errorMessage)));
+      return false;
+    }
+
     await eventsService.addWalletPath(filePath);
```
Comment (brusherru) [inline app/redux/wallet/actions.ts]: Why not just validate the wallet file within `addWalletPath` handler?
Then there will be no changes required at all.

File: desktop/main/walletFile.ts [hunk 2]
```diff
@@ -270,6 +270,15 @@ export const copyWalletFile = async (filePath: string, outputDir: string) => {
...
 
+export const isWalletFileValid = async (filePath: string) => {
+  try {
+    await loadRawWallet(filePath);
+    return true;
+  } catch (error) {
+    return false;
+  }
+};
+
```
Comment (brusherru) [inline desktop/main/walletFile.ts]: Absolutely wrong validity check.
It sounds like a guard, but actually it does an I/O and does not check format except that it is JSON.
Remove it.

**Review by brusherru — CHANGES_REQUESTED** [review]
You have overcomplicated it, while didn't make it robust at all :-\

File: app/components/auth/DragAndDrop.tsx
Comment (maparr) [reply app/components/auth/DragAndDrop.tsx:1]: https://github.com/spacemeshos/smapp/assets/54288612/9ffa7c1e-f5d7-4e58-9985-727856aebd55

Comment (brusherru) [reply app/components/auth/DragAndDrop.tsx:1]: Okay, got it.
It is actually about `files?.length` and not related to `fileName` (so `Props` is valid).

File: app/redux/wallet/actions.ts [hunk 3]
```diff
@@ -275,15 +275,23 @@ export const restoreFile = ({ filePath }: { filePath: string }) => async (
...
-        addErrorPrefix('Can not restore wallet file\n', error as Error)
-      )
+    const result = await eventsService.addWalletPath(filePath);
+
+    if (result?.length) {
+      return true;
+    }
+
+    const errorMessage = `Wallet file ${filePath} is invalid.\nPlease verify it and import the wallet file once again.`;
+    dispatch(setUiError(new Error(errorMessage)));
```
Comment (brusherru) [inline app/redux/wallet/actions.ts]: No need to add a specific handler here and overcomplicate return type of `addWalletPath`

File: app/components/auth/DragAndDrop.tsx
Comment (maparr) [reply app/components/auth/DragAndDrop.tsx:1]: yes

File: desktop/main/Wallet.ts [hunk 4]
```diff
@@ -160,7 +159,13 @@ const subscribe = () => {
...
   );
 
-  ipcMain.handle(ipcConsts.W_M_ADD_WALLET_PATH, (_, filePath: string) => {
+  ipcMain.handle(ipcConsts.W_M_ADD_WALLET_PATH, async (_, filePath: string) => {
+    const isWalletFileValidStatus = await isWalletFileValid(filePath);
+
+    if (!isWalletFileValidStatus) {
+      return false;
+    }
+
```
Comment (brusherru) [inline desktop/main/Wallet.ts]: Please use consistent types. Since it returns `string[]` — it should not return `false` for "invalidity" case. But it should throw an Error instead (and it is already handled "for free").

File: desktop/main/walletFile.ts [hunk 5]
```diff
@@ -270,6 +270,55 @@ export const copyWalletFile = async (filePath: string, outputDir: string) => {
...
+    const { crypto, meta } = wallet;
+
+    const isWalletFileFieldsValid =
+      typeof meta.displayName === 'string' &&
+      typeof meta.created === 'string' &&
+      typeof meta.remoteApi === 'string' &&
+      typeof meta.type === 'string' &&
+      typeof crypto.cipher === 'string' &&
+      typeof crypto.cipherText === 'string';
```
Comment (brusherru) [inline desktop/main/walletFile.ts]: Move this into `shared/types/guards.ts` module and name function `isWalletMeta`.

File: desktop/main/walletFile.ts [hunk 6]
```diff
@@ -270,6 +270,55 @@ export const copyWalletFile = async (filePath: string, outputDir: string) => {
...
+        kdfparams: { dklen, hash, iterations, salt },
+      } = crypto;
+
+      return (
+        typeof iv === 'string' &&
+        kdf === 'PBKDF2' &&
+        typeof dklen === 'number' &&
+        hash === 'SHA-512' &&
+        typeof iterations === 'number' &&
+        typeof salt === 'string'
```
Comment (brusherru) [inline desktop/main/walletFile.ts]: You can add it to `isWalletGCMEncrypted` guard.

File: desktop/main/walletFile.ts [hunk 7]
```diff
@@ -270,6 +270,55 @@ export const copyWalletFile = async (filePath: string, outputDir: string) => {
   return newFilePath;
 };
 
+export const isWalletFileValid = async (filePath: string) => {
```
Comment (brusherru) [inline desktop/main/walletFile.ts]: This entire function should not persist in such a form.
Instead, please implement `isWalletMeta` and `isWalletFile` guards within `shared/types/guards.ts` module. And use it.

Pay attention, that they should not do any I/O or side effects.

File: desktop/main/walletFile.ts [hunk 8]
```diff
@@ -153,7 +153,7 @@ export const encryptWallet = async (
 
 export const loadRawWallet = async (path: string): Promise<WalletFile> => {
   const fileContent = await fs.readFile(path, { encoding: 'utf8' });
-  return JSON.parse(fileContent) as WalletFile;
+  return JSON.parse(fileContent);
```
Comment (brusherru) [inline desktop/main/walletFile.ts]: After implementing guards, do:
```suggestion
  const content = JSON.parse(fileContent);
  if (!isWalletFile(content)) {
    throw new Error(`File ${path} is not a valid wallet file`);
  }
  return content;
```

No more changes are needed.

File: tests/walletFiles.spec.ts
Comment (brusherru) [inline tests/walletFiles.spec.ts:1]: You can keep tests (but move them in a separate module: `guards.spec.ts`) for newly created guards and re-use these fixtures.

**Review by brusherru — CHANGES_REQUESTED** [review]

**Comment by monikasmolarek** [comment]
@maparr please let me know once every suggestion resolved and I could start testing on all 3 OSes

File: desktop/main/Wallet.ts [hunk 9]
```diff
@@ -160,12 +159,34 @@ const subscribe = () => {
...
+      try {
+        const oldWalletFiles = StoreService.get('walletFiles');
+        const newWalletFiles = R.uniq([...oldWalletFiles, filePath]);
+        StoreService.set('walletFiles', newWalletFiles);
+        return { error: null, result: newWalletFiles };
+      } catch (err: any) {
+        return { error: err.message, result: null };
+      }
+    }
```
Comment (brusherru) [inline desktop/main/Wallet.ts]: 1. Do not repeat yourself. If you want to have more user-friendly error message about invalid JSON — catch & rethrow the error inside `loadRawWallet` instead.
2. We already have type for `{ error, result }` and helper function...
3. `Error` type is serializing automatically into `{ message, stack }` when sent via IPC.

```suggestion
      try {
        await loadRawWallet(filePath);
        const oldWalletFiles = StoreService.get('walletFiles');
        const newWalletFiles = R.uniq([...oldWalletFiles, filePath]);
        StoreService.set('walletFiles', newWalletFiles);
        return createIpcResponse(null, newWalletFiles);
      } catch (err: any) {
        return createIpcResponse(err, null);
      }
    }
```

File: desktop/main/Wallet.ts [hunk 10]
```diff
@@ -160,12 +159,34 @@ const subscribe = () => {
...
-  });
+  ipcMain.handle(
+    ipcConsts.W_M_ADD_WALLET_PATH,
+    async (
+      _,
+      filePath: string
+    ): Promise<{
+      error: string | null;
+      result: string[] | null;
+    }> => {
```
Comment (brusherru) [inline desktop/main/Wallet.ts]: No need to reinvent such types...
```suggestion
    ): Promise<IpcResponse<string[]>> => {
```

File: shared/types/guards.ts [hunk 11]
```diff
@@ -47,21 +49,59 @@ export const isReward = (a: any): a is Reward =>
...
   a: any
 ): a is WalletSecretsEncryptedLegacy =>
   isWalletSecretsEncrypted(a) && a.cipher === 'AES-128-CTR';
 
 export const isWalletSecrets = (a: any): a is WalletSecrets =>
-  a && a.mnemonic && a.accounts && a.contacts;
+  Boolean(a && a.mnemonic && a.accounts && a.contacts);
+
+export const isWalletHasStructure = (a: any): a is WalletFile =>
+  Boolean(a && a.meta && a.crypto);
```
Comment (brusherru) [inline shared/types/guards.ts]: It is not enough to ensure the type. Wrong guard.
```suggestion
```

File: shared/types/guards.ts [hunk 12]
```diff
@@ -47,21 +49,59 @@ export const isReward = (a: any): a is Reward =>
...
+      return false;
+    }
+
+    return isWalletGCMEncrypted(crypto) || isWalletLegacyEncrypted(crypto);
+  } catch (error) {
+    // eslint-disable-next-line no-console
+    console.error(error);
+    return false;
+  }
+};
```
Comment (brusherru) [inline shared/types/guards.ts]: 1. All guards are pure functions with object property checks. No need to wrap it into try-catch, if there is some exception has occurred — it means that there is a bug in the code.
2. It is not a TS guard.

```suggestion
export const isWalletFile = (wallet: any): wallet is WalletFile => (
   wallet &&
   isWalletMeta(wallet.meta) &&
   isWalletSecretsEncrypted(wallet.crypto) &&
   (
     isWalletGCMEncrypted(wallet.crypto) ||
     isWalletLegacyEncrypted(wallet.crypto)
   );
```

File: tests/fixtures/my_wallet_gcm.json
Comment (brusherru) [inline tests/fixtures/my_wallet_gcm.json:1]: What's changed? What is the purpose?

File: tests/shared/types/guards.spec.ts
Comment (brusherru) [inline tests/shared/types/guards.spec.ts:1]: 👍

File: tests/walletFiles.spec.ts
Comment (brusherru) [inline tests/walletFiles.spec.ts:1]: 👍

File: app/infra/eventsService/eventsService.ts [hunk 13]
```diff
@@ -137,8 +137,12 @@ class EventsService {
...
     ipcRenderer.invoke(ipcConsts.W_M_BACKUP_WALLET, filePath);
 
-  static addWalletPath = (filePath: string) =>
-    ipcRenderer.invoke(ipcConsts.W_M_ADD_WALLET_PATH, filePath);
+  static addWalletPath = (
+    filePath: string
+  ): Promise<{
+    error: string | null;
+    result: string[] | null;
+  }> => ipcRenderer.invoke(ipcConsts.W_M_ADD_WALLET_PATH, filePath);
```
Comment (brusherru) [inline app/infra/eventsService/eventsService.ts]:
```suggestion
  ): Promise<IpcResponse<string[]>> => ipcRenderer.invoke(ipcConsts.W_M_ADD_WALLET_PATH, filePath);
```

File: app/redux/wallet/actions.ts [hunk 14]
```diff
@@ -274,18 +274,18 @@ export const removeFromContacts = ({
...
-    dispatch(
-      setUiError(
-        addErrorPrefix('Can not restore wallet file\n', error as Error)
-      )
+  const { error } = await eventsService.addWalletPath(filePath);
+
+  if (error) {
+    const errorMessage = addErrorPrefix(
+      'Cannot restore wallet file\n',
+      new Error(error)
```
Comment (brusherru) [inline app/redux/wallet/actions.ts]:
```suggestion
      new Error(error.message)
```

**Review by brusherru — CHANGES_REQUESTED** [review]

File: tests/fixtures/my_wallet_gcm.json
Comment (maparr) [reply tests/fixtures/my_wallet_gcm.json:1]: I checked, the spaces only. Autosave. I can revert this file.

**Comment by maparr** [comment]
@monikasmolarek u can take a look.

**Review by monikasmolarek — APPROVED** [review]
all good from the user perspective. There's just one corner case: 
1. try to load an incorrect wallet
1. get the error msg
1. fix the file
1. try to load it again
-in this case it is not checked/assessed, the path is remembered as incorrect, only ulnikning this path and selecting again will let us choose the same file. 
But I don’t think it it's any crucial or important to cover, especially for this smapp version

**Review by brusherru — APPROVED** [review]
LGTM
