### PR TITLE
Fix copying address

### LINKED ISSUE #1133: Do not copy address on opening Request screen
Sentry Issue: [SMAPP-18C](https://spacemesh.sentry.io/issues/3924923074/?referrer=github_integration)

### Environment:
Smapp: v0.2.11

### Describe the bug
Clicking the 'request' button overwrites the original clipboard buffer

### Steps to reproduce
1. Put some known text into the windows copy/paste buffer using CTRL+C
2. Hit the 'Request' button on the Wallet screen
3. Use CTRL +V in notepad

### Expected behavior
Overwriting the copy/paste buffer in windows should be an explicit user action. E.g. clicking on the "copy" button next to the address, instead of updating the clipboard on opening the screen.

### Actual behavior
It overwrites the clipboard buffer on entering the Request screen.

---
Also, it will be good to add icons (copy, explorer) to the Wallet screen for GUI, when you have more than one account in the wallet (when it renders dropdown).

### PR DESCRIPTION
**Pull request by maparr**
It closes #1133 

screenshot :
Screenshot 2023-02-17 at 23 08 45

### CODE REVIEW

File: app/components/wallet/AccountsOverview.tsx [hunk 1]
```diff
@@ -141,6 +187,42 @@ const AccountsOverview = () => {
   const balance = balances[address];
   const { value, unit } = parseSmidge(balance?.currentState?.balance || 0);
 
+  const handleCopy = async (e: React.MouseEvent, value: string) => {
+    e.stopPropagation();
+    await navigator.clipboard.writeText(value);
+    setIsCopied(value);
+    clearTimeout(copyTimeout);
+    copyTimeout = setTimeout(() => setIsCopied(null), 3000);
+  };
```
Comment (brusherru) [inline app/components/wallet/AccountsOverview.tsx]: Let's avoid code duplication and extract all these code in separate components `basicComponents/copyButton.tsx` and `basicComponents/explorerButton.tsx`.
They also should be reused in `Address` component.

**Review by brusherru — CHANGES_REQUESTED** [review]
From a UX perspective — I believe this is a really good improvement 👍 
Just need to refactor the code a bit and will be perfect!

File: app/basicComponents/CopyButton.tsx [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+  cursor: pointer;
+  &:hover {
+    opacity: 0.5;
+  }
+  &:active {
+    transform: translate3d(2px, 2px, 0);
+  }
+`;
+
+const CopyButton = ({ onClickCopy, secondary, children, isCopied }: Props) => {
```
Comment (brusherru) [inline app/basicComponents/CopyButton.tsx]: Let's move `useCopy` hook in this component.
So `CopyButton` encapsulates the look and behavior.

And instead of `onClickCopy` let's set the `value` prop with string to copy.

Comment (brusherru) [reply app/basicComponents/CopyButton.tsx]: Btw, instead of having all these states `copiedAddress` and `isCopied` in this hook, this `CopyButton` component can have also `onCopy: (value: string) => void` property, which will be called beside copying `value` to the clipboard.

Then, `AccountOverview` can have:
```
let t = 0;
const [lastCopiedAddress, setLastCopiedAddress] = useState<string | null>(null);
const handleCopyAddress = (address: string) => {
  await navigator.clipboard.writeText(address);
  setLastCopiedAddress(address):
  clearTimeout(t);
  t = setTimeout(() => setLastCopiedAddress(null), 5000);
};

// and then use <CopyButton value={...} onClick={handleCopyAddress} />
```
Which can be used to show this "COPIED" text ;)

p.s.
And then it seems like we don't need any special hook for this...

**Review by brusherru — CHANGES_REQUESTED** [review]

File: app/basicComponents/CopyButton.tsx [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+  return (
+    <Wrapper onClick={onClickCopy}>
+      {children}
+      {!isCopied && <CopyIcon secondary={secondary} />}
```
Comment (brusherru) [inline app/basicComponents/CopyButton.tsx]: It seems to me that the proper name will be `isCustomRenderer` instead of `isCopied`, or in our case, we can just check that we have this custom renderer:
```suggestion
      {children}
      {!children && <CopyIcon secondary={secondary} />}
```

Comment (maparr) [reply app/basicComponents/CopyButton.tsx]: Renamed. Exactly in this case where we have to show CopyIcon for 3-5 seconds depending on the timer. And after it shows CopyIcon again.  Not possible to reuse children.

File: app/basicComponents/CopyButton.tsx (hunk 2 above)
Comment (maparr) [reply app/basicComponents/CopyButton.tsx]: Moved. We have different places where we show Copied text, and in case of reuse handler and not copying past it from place to place, not possible to avoid the hook or hide this functionality only in the button. 
What is possible, to create 2 different components for different cases and use them with the internal handler for each component, and these handlers will be possible to replace with 1 hook and separate it from components folder and reuse for each component, for example `CopyButton` and `CopyTextSection`

File: app/basicComponents/CopyButton.tsx [hunk 4]
```diff
@@ -0,0 +1,59 @@
+import React from 'react';
+import styled from 'styled-components';
+
+type Props = {
+  secondary?: boolean;
+  onClick: (value: string | null) => void;
```
Comment (brusherru) [inline app/basicComponents/CopyButton.tsx]:
```suggestion
  onClick: (value: string) => void;
```

**Review by brusherru — DISMISSED** [review]
One note, in the rest LGTM

**Review by brusherru — APPROVED** [review]

**Review by monikasmolarek — APPROVED** [review]
👌
