### PR TITLE
Fix:write after end log rotator

### LINKED ISSUE #1191: ENOENT while trying to backup wallet to the file
### Environment

* Smapp version: 0.2.12 + custom from fix/1167
* Node version: v0.2.23-beta.0
* OS: Windows 10 Home (on Mac seems to be ok)

### Describe the bug
If we open a wallet from file, from any custom directory, if we want to then back it up to the file, we get the error

Screenshot 2023-03-13 at 19 21 16
 
### Steps to reproduce

1.  Open Smapp
2.  Click "OPEN AN EXISTING WALLET"
3.  Choose the file located anywhere except the Spacemesh App directory
4. Click "BACKUP YOUR WALLET"
5. Choose the FILE BACKUP

### Expected behavior

The Wallet file should be backed up in the default (Documents) directory, we should get the confirmation screen with the link to the json file location. 

### Actual behavior

https://user-images.githubusercontent.com/89876259/224796193-d2e102bc-6b04-4695-9d8f-35fafc50cb9e.mp4

https://user-images.githubusercontent.com/89876259/224796198-5f7cb02d-2c19-4cb4-a955-c63800c25ab5.mp4

### Logs

```
18:40:00.387 > GlobalStateService.AccountDataQuery called:   {"filter":{"accountId":{"address":"stest1qqqqqqxtrwh7cmdspvk5jhe3493vg3cnu2ejtjc2335wc"},"accountDataFlags":2},"maxResults":100,"offset":0}
18:40:01.074 > NodeService.Echo called:   {"msg":{"value":"ready"}}
18:40:05.544 > SmesherService.IsSmeshing called:   {}
18:40:05.546 > SmesherService.PostSetupStatus called:   {}
18:41:00.394 > GlobalStateService.AccountDataQuery called:   {"filter":{"accountId":{"address":"stest1qqqqqqxtrwh7cmdspvk5jhe3493vg3cnu2ejtjc2335wc"},"accountDataFlags":2},"maxResults":100,"offset":0}
18:42:00.398 > GlobalStateService.AccountDataQuery called:   {"filter":{"accountId":{"address":"stest1qqqqqqxtrwh7cmdspvk5jhe3493vg3cnu2ejtjc2335wc"},"accountDataFlags":2},"maxResults":100,"offset":0}
18:42:01.076 > NodeService.Echo called:   {"msg":{"value":"ready"}}
18:43:00.409 > GlobalStateService.AccountDataQuery called:   {"filter":{"accountId":{"address":"stest1qqqqqqxtrwh7cmdspvk5jhe3493vg3cnu2ejtjc2335wc"},"accountDataFlags":2},"maxResults":100,"offset":0}
18:44:00.414 > GlobalStateService.AccountDataQuery called:   {"filter":{"accountId":{"address":"stest1qqqqqqxtrwh7cmdspvk5jhe3493vg3cnu2ejtjc2335wc"},"accountDataFlags":2},"maxResults":100,"offset":0}
18:44:01.076 > NodeService.Echo called:   {"msg":{"value":"ready"}}
18:45:00.425 > GlobalStateService.AccountDataQuery called:   {"filter":{"accountId":{"address":"stest1qqqqqqxtrwh7cmdspvk5jhe3493vg3cnu2ejtjc2335wc"},"accountDataFlags":2},"maxResults":100,"offset":0}
18:45:05.546 > SmesherService.IsSmeshing called:   {}
18:45:05.548 > SmesherService.PostSetupStatus called:   {}
18:46:00.437 > GlobalStateService.AccountDataQuery called:   {"filter":{"accountId":{"address":"stest1qqqqqqxtrwh7cmdspvk5jhe3493vg3cnu2ejtjc2335wc"},"accountDataFlags":2},"maxResults":100,"offset":0}
18:46:01.079 > NodeService.Echo called:   {"msg":{"value":"ready"}}

```

### How to fix

### PR DESCRIPTION
**Pull request by maparr**
It closes #1191

### CODE REVIEW

File: desktop/NodeManager.ts [hunk 1]
```diff
@@ -467,23 +470,28 @@ class NodeManager extends AbstractManager {
...
 
         logger.error('spawnNode', error);
+
+        return;
       }
+
+      this.nodeLogStream?.write(data);
     });
-    this.nodeProcess.stdout?.pipe(logFileStream);
-    this.nodeProcess.stderr?.pipe(logFileStream);
```
Comment (brusherru) [inline desktop/NodeManager.ts:449]: Not sure we really need it, but I believe it is better to collect both outputs. Is it a problem?

Comment (maparr) [reply desktop/NodeManager.ts:449]: Checked. Worked as expected.

Comment (brusherru) [reply desktop/NodeManager.ts:449]: I think we need to add a second argument to them:
```
    this.nodeProcess.stdout?.pipe(this.nodeLogStream, { end: false });
    this.nodeProcess.stderr?.pipe(this.nodeLogStream, { end: false });
```
Otherwise, we can end up with the same error, having `nodeLogStream` closed via `stdout.pipe`, while `stderr` may still have something to write there... Wdyt?

**Review by monikasmolarek — APPROVED** [review]
tested over the weekend, looks ok

**Review by brusherru — APPROVED** [review]
👌
